CREATE TABLE IF NOT EXISTS mini_excavation_photo (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  site_id BIGINT NULL COMMENT '场地ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  reporter_name VARCHAR(64) NOT NULL COMMENT '上报人',
  plate_no VARCHAR(32) NULL COMMENT '识别车牌',
  recognition_source VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '识别来源',
  photo_type VARCHAR(32) NOT NULL DEFAULT 'EXCAVATION' COMMENT '照片类型',
  file_url VARCHAR(500) NOT NULL COMMENT '图片地址',
  longitude DECIMAL(12,6) NULL COMMENT '经度',
  latitude DECIMAL(12,6) NULL COMMENT '纬度',
  shoot_time DATETIME NOT NULL COMMENT '拍摄时间',
  remark VARCHAR(255) NULL COMMENT '备注',
  audit_status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED' COMMENT '审核状态',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted INT NOT NULL DEFAULT 0,
  KEY idx_mini_photo_project (tenant_id, project_id, shoot_time),
  KEY idx_mini_photo_site (tenant_id, site_id, shoot_time),
  KEY idx_mini_photo_user (tenant_id, user_id, shoot_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序出土拍照记录';

CREATE TABLE IF NOT EXISTS mini_checkin_exception_apply (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  checkin_id BIGINT NOT NULL COMMENT '打卡记录ID',
  project_id BIGINT NULL COMMENT '项目ID',
  site_id BIGINT NULL COMMENT '场地ID',
  user_id BIGINT NOT NULL COMMENT '申报人ID',
  reporter_name VARCHAR(64) NOT NULL COMMENT '申报人名称',
  exception_type VARCHAR(64) NOT NULL COMMENT '异常类型',
  reason VARCHAR(500) NOT NULL COMMENT '申报原因',
  attachment_urls VARCHAR(2000) NULL COMMENT '附件地址',
  status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED' COMMENT '状态',
  linked_event_id BIGINT NULL COMMENT '关联事件ID',
  source_channel VARCHAR(32) NOT NULL DEFAULT 'MINI' COMMENT '来源渠道',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted INT NOT NULL DEFAULT 0,
  KEY idx_mini_checkin_apply_user (tenant_id, user_id, status),
  KEY idx_mini_checkin_apply_checkin (tenant_id, checkin_id),
  KEY idx_mini_checkin_apply_event (tenant_id, linked_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序打卡异常申报';

CREATE TABLE IF NOT EXISTS mini_delay_apply (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  biz_type VARCHAR(32) NOT NULL DEFAULT 'PROJECT' COMMENT '业务类型',
  biz_id BIGINT NULL COMMENT '业务ID',
  project_id BIGINT NULL COMMENT '项目ID',
  site_id BIGINT NULL COMMENT '场地ID',
  user_id BIGINT NOT NULL COMMENT '申报人ID',
  reporter_name VARCHAR(64) NOT NULL COMMENT '申报人名称',
  requested_end_time DATETIME NOT NULL COMMENT '申请延期到',
  reason VARCHAR(500) NOT NULL COMMENT '延期原因',
  attachment_urls VARCHAR(2000) NULL COMMENT '附件地址',
  status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED' COMMENT '状态',
  linked_event_id BIGINT NULL COMMENT '关联事件ID',
  source_channel VARCHAR(32) NOT NULL DEFAULT 'MINI' COMMENT '来源渠道',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted INT NOT NULL DEFAULT 0,
  KEY idx_mini_delay_apply_user (tenant_id, user_id, status),
  KEY idx_mini_delay_apply_project (tenant_id, project_id, requested_end_time),
  KEY idx_mini_delay_apply_event (tenant_id, linked_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序延期申报';

CREATE TABLE IF NOT EXISTS mini_feedback (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id BIGINT NOT NULL COMMENT '租户ID',
  feedback_type VARCHAR(32) NOT NULL COMMENT '反馈类型',
  project_id BIGINT NULL COMMENT '项目ID',
  site_id BIGINT NULL COMMENT '场地ID',
  user_id BIGINT NOT NULL COMMENT '反馈人ID',
  reporter_name VARCHAR(64) NOT NULL COMMENT '反馈人名称',
  title VARCHAR(128) NOT NULL COMMENT '标题',
  content VARCHAR(1000) NOT NULL COMMENT '内容',
  attachment_urls VARCHAR(2000) NULL COMMENT '附件地址',
  report_address VARCHAR(255) NULL COMMENT '上报地址',
  status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED' COMMENT '状态',
  handler_id BIGINT NULL COMMENT '处理人ID',
  handler_name VARCHAR(64) NULL COMMENT '处理人名称',
  close_time DATETIME NULL COMMENT '关闭时间',
  close_remark VARCHAR(500) NULL COMMENT '关闭说明',
  linked_event_id BIGINT NULL COMMENT '关联事件ID',
  source_channel VARCHAR(32) NOT NULL DEFAULT 'MINI' COMMENT '来源渠道',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted INT NOT NULL DEFAULT 0,
  KEY idx_mini_feedback_user (tenant_id, user_id, status),
  KEY idx_mini_feedback_project (tenant_id, project_id, status),
  KEY idx_mini_feedback_event (tenant_id, linked_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序问题反馈';
